version: "3.7"

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__RBAC: "true"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/external/m5-forecasting-accuracy:/data  # локальная папка с CSV

  airflow-webserver:
    build: .
    depends_on:
      - postgres
      - minio
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - airflow_logs:/opt/airflow/logs
      - ./data/external/m5-forecasting-accuracy:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  airflow-scheduler:
    build: .
    depends_on:
      - postgres
      - minio
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - airflow_logs:/opt/airflow/logs
      - ./data/external/m5-forecasting-accuracy:/opt/airflow/data
    command: scheduler
    restart: always

  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    command: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

volumes:
  postgres_data:
  airflow_logs:
