stages:
  load:
    cmd: python src/load.py
    deps:
      - src/load.py
      - data/external/

  features:
    cmd: python src/features.py --input data/processed/df_sales_train_validation.csv --output_train data/processed/train_df.csv --output_test data/processed/val_df.csv
    deps:
      - src/features.py
      - data/processed/df_sales_train_validation.csv
    outs:
      - data/processed/train_df.csv
      - data/processed/val_df.csv

  train:
    cmd: python src/train.py --train data/processed/train_df.csv --model models/model.pkl
    deps:
      - src/train.py
      - data/processed/train_df.csv 
    outs:
      - models/model.pkl


  test:
    cmd: python src/test.py --test data/processed/val_df.csv --model models/model.pkl
    deps:
      - src/test.py
      - data/processed/val_df.csv
      - models/model.pkl

